# Generated by Django 6.1.1 on 2026-10-04 05:53

import django.core.validators
import django.db.models.deletion
import inventory.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('account_notes', models.TextField(blank=True, help_text='Account name, login email, support PIN location. Never store passwords here.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
                ('expires_on', models.DateField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('dns_provider', models.ForeignKey(blank=True, help_text='Leave empty when DNS is hosted at the registrar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dns_domains', to='inventory.provider')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_domains', to='inventory.provider')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('home', 'Home server'), ('vps', 'VPS'), ('shared', 'Shared hosting')], max_length=10)),
                ('host', models.CharField(blank=True, max_length=253, verbose_name='public IP or hostname')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Leave empty for hardware you own, such as the home server.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='inventory.provider')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(blank=True, help_text='For example app.example.com', max_length=253, verbose_name='subdomain or hostname')),
                ('url', models.URLField(blank=True, help_text='Checked by the reachability monitor.', verbose_name='URL')),
                ('repo_url', models.URLField(blank=True, verbose_name='repository URL')),
                ('status', models.CharField(choices=[('live', 'Live'), ('development', 'In development'), ('paused', 'Paused'), ('retired', 'Retired')], default='live', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_check_ok', models.BooleanField(editable=False, null=True)),
                ('last_check_status_code', models.PositiveSmallIntegerField(editable=False, null=True)),
                ('last_check_response_ms', models.PositiveIntegerField(editable=False, null=True)),
                ('last_check_error', models.CharField(blank=True, editable=False, max_length=255)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='inventory.server')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default=inventory.models.default_currency, max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a three-letter ISO code such as USD.')])),
                ('billing_cycle', models.PositiveSmallIntegerField(choices=[(1, 'Monthly'), (3, 'Quarterly'), (6, 'Every 6 months'), (12, 'Yearly'), (24, 'Every 2 years'), (36, 'Every 3 years')], default=12)),
                ('next_renewal', models.DateField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Untick for cancelled subscriptions to keep them as history.')),
                ('notes', models.TextField(blank=True)),
                ('domain', models.ForeignKey(blank=True, help_text='Set when this subscription is a domain registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='inventory.domain')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='inventory.provider')),
                ('server', models.ForeignKey(blank=True, help_text='Set when this subscription pays for a server plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='inventory.server')),
            ],
            options={
                'ordering': ['next_renewal', 'name'],
            },
        ),
    ]
