# Generated by Django 6.1.1 on 2026-10-04 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='url',
            field=models.URLField(blank=True, help_text='Checked by the reachability monitor.', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='URL'),
        ),
    ]
