# Generated by Django 6.1.1 on 2026-10-05 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_restrict_app_url_to_http'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='monitoring_since',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('domain_expiry', 'Domain expiry'), ('subscription_renewal', 'Subscription renewal'), ('tls_expiry', 'TLS certificate expiry'), ('downtime', 'Downtime'), ('sync_failure', 'Provider sync failure')], max_length=30)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('raised_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_severity', models.CharField(blank=True, choices=[('warning', 'Warning'), ('critical', 'Critical')], help_text='The highest severity an email has gone out for.', max_length=10)),
                ('resolution_emailed', models.BooleanField(default=False)),
                ('email_error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='AppCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('ok', models.BooleanField()),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('response_ms', models.PositiveIntegerField(null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('tls_expires_at', models.DateTimeField(null=True, verbose_name='TLS certificate expires')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('record_type', models.CharField(max_length=10, verbose_name='type')),
                ('name', models.CharField(max_length=253)),
                ('content', models.TextField()),
                ('proxied', models.BooleanField(null=True)),
                ('ttl', models.PositiveIntegerField(help_text='1 means automatic.', verbose_name='TTL')),
            ],
            options={
                'verbose_name': 'DNS record',
                'ordering': ['domain', 'name', 'record_type', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('status_changed_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='app',
            name='down_since',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='last_check_tls_expires_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='TLS certificate expires'),
        ),
        migrations.AddField(
            model_name='domain',
            name='dns_zone_status',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='DNS zone status'),
        ),
        migrations.AddField(
            model_name='domain',
            name='registrar_status',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='provider',
            name='integration',
            field=models.CharField(blank=True, choices=[('cloudflare', 'Cloudflare'), ('godaddy', 'GoDaddy'), ('digitalocean', 'DigitalOcean'), ('hostinger', 'Hostinger')], help_text='The provider API homebase reads live data from, when its token is configured.', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='sync_attempted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='sync_error',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='sync_succeeded_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='sync_summary',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='external_id',
            field=models.CharField(blank=True, help_text='The droplet or VM ID at the provider. Set by the provider sync; clear it to unlink.', max_length=100, verbose_name='provider ID'),
        ),
        migrations.AddField(
            model_name='server',
            name='live_status',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='external_id',
            field=models.CharField(blank=True, help_text='The billing ID at the provider. Set by the provider sync, which then keeps cost, renewal date, and auto-renew up to date. Clear it to unlink.', max_length=100, verbose_name='provider ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monthly'), (3, 'Quarterly'), (6, 'Every 6 months'), (12, 'Yearly'), (24, 'Every 2 years'), (36, 'Every 3 years'), (48, 'Every 4 years')], default=12),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('integration', ''), _negated=True), fields=('integration',), name='unique_provider_integration'),
        ),
        migrations.AddConstraint(
            model_name='server',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('provider', 'external_id'), name='unique_server_external_id'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('provider', 'external_id'), name='unique_subscription_external_id'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at', None)), fields=('key',), name='unique_open_alert_key'),
        ),
        migrations.AddField(
            model_name='appcheck',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='inventory.app'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='inventory.domain'),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels', to='inventory.provider'),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='server',
            field=models.ForeignKey(blank=True, help_text='The machine that runs the connector.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tunnels', to='inventory.server'),
        ),
        migrations.AddIndex(
            model_name='appcheck',
            index=models.Index(fields=['app', 'checked_at'], name='inventory_a_app_id_333ca6_idx'),
        ),
        migrations.AddConstraint(
            model_name='dnsrecord',
            constraint=models.UniqueConstraint(fields=('domain', 'external_id'), name='unique_dns_record_external_id'),
        ),
        migrations.AddConstraint(
            model_name='tunnel',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_tunnel_external_id'),
        ),
    ]
